Make repo ready for CNCF
piraeusdatastore/piraeus pull request #64
Opened 2021-01-27 13:39 UTC by WanzenBug

Adds:
* Code of conduct
* Maintainers list
* Contributing guide
* governance policy

Changed:
* moved yaml deployment to `/legacy`
* updated README to point to Piraeus Operator deployment

2021-01-27 13:56 UTC, rck requested changes

2021-01-27 13:56 UTC, rck commented on MAINTAINERS.md
> +## Maintainers
maybe add some "in alphabetical order" to make clear this does not imply anything else than that.

2021-01-27 13:59 UTC, rck commented
while these are established standards, do we want some S-o-b from all that will be maintainers? Quite frankly I think this would be a good idea in this case.

2021-01-27 14:04 UTC, rck approved these changes

2021-01-27 14:06 UTC, rck commented
LGTM, feel free to eventually add `Signed-off-by: Roland Kammerer <roland.kammerer@linbit.com>`

2021-01-28 08:33 UTC, JoelColledge commented on CONTRIBUTING.md
> +Welcome to Piraeus! Piraeus consists several repositories under the organization.
```suggestion
Welcome to Piraeus! Piraeus consists of several repositories under the organization.
```

2021-01-28 08:33 UTC, JoelColledge commented on CONTRIBUTING.md
> +- If you find some redundant codes, try to remove them!
```suggestion
- If you find some redundant code, try to remove it
```

2021-01-28 08:33 UTC, JoelColledge commented on CONTRIBUTING.md
> +- If you find a typo, try to fix it!
"!" on every point are not really English style.

2021-01-28 08:33 UTC, JoelColledge commented on CONTRIBUTING.md
> +- If you can help to improve documents, it could not be better!
```suggestion
- If you can help to improve documentation, that is great
```

2021-01-28 08:33 UTC, JoelColledge commented on CONTRIBUTING.md
> +- If you find document incorrect, just do it and fix that!
```suggestion
- If you find documentation incorrect, go ahead and fix it
```

2021-01-28 08:33 UTC, JoelColledge commented on CONTRIBUTING.md
> +please remember to remove sensitive data from your issue description. Sensitive data could be password, secret key,
```suggestion
Please remember to remove sensitive data from your issue description. Sensitive data includes passwords, secret keys,
```

2021-01-28 08:33 UTC, JoelColledge commented on CONTRIBUTING.md
> +- reply to other's issues if you could;
```suggestion
- reply to issues if you can;
```

2021-01-28 08:33 UTC, JoelColledge commented on CONTRIBUTING.md
> +- help solve other user's problems;
```suggestion
- help solve other users' problems;
```

2021-01-28 08:33 UTC, JoelColledge commented on CONTRIBUTING.md
> +- help review other's PR design;
```suggestion
```

I don't what the difference is between this point and the next one.

2021-01-28 08:33 UTC, JoelColledge commented on CONTRIBUTING.md
> +- help review other's codes in PR;
```suggestion
- help review the code from other contributors in PRs;
```

2021-01-28 08:33 UTC, JoelColledge commented on CONTRIBUTING.md
> +It is also welcomed to join Piraeus team if you are willing to participate in Piraeus community continuously and keep active.
```suggestion
It is also welcomed that you join the Piraeus team if you are willing to participate in the Piraeus community regularly.
```

2021-01-28 08:33 UTC, JoelColledge commented on CONTRIBUTING.md
> +- Have submitted multi PRs to the community
```suggestion
- Have submitted multiple PRs to the community
```

2021-01-28 08:33 UTC, JoelColledge commented on CONTRIBUTING.md
> +- Be active in the community, may including but not limited
```suggestion
- Be active in the community; may include but not limited to
```

2021-01-28 08:33 UTC, JoelColledge commented on CONTRIBUTING.md
> +- Contact via the [community](./README.md#community) channels offline
```suggestion
- Contact the team via the [community](./README.md#community) channels
```

2021-01-28 08:33 UTC, JoelColledge commented on MAINTAINERS.md
> +in alphabetical order:
```suggestion
In alphabetical order:
```

2021-01-28 09:18 UTC, JoelColledge approved these changes
Looks good. You're welcome to add `Signed-off-by: Joel Colledge <joel.colledge@linbit.com>` to the commit message too.

2021-02-02 19:47 UTC, merged