Implement multi-arch build for piraeus-client
piraeusdatastore/piraeus pull request #76
Opened 2021-05-04 18:41 UTC by Jukie

Closes ##74

I didn't remove the Makefile with this PR in case that's used elsewhere. If it isn't we should be able to drop it.

2021-05-04 18:44 UTC, Jukie commented on .github/workflows/build-piraeus-client.yaml
> +          TAGS="${DOCKERHUB_IMAGAE}:${LINSTOR_CLIENT_VERSION},${DOCKERHUB_IMAGAE}:${SHORT_VERSION}",${DOCKERHUB_IMAGAE}:latest,${QUAYIO_IMAGE}:${LINSTOR_CLIENT_VERSION},${QUAYIO_IMAGE}:${SHORT_VERSIO
Could probably clean this up

2021-05-05 06:17 UTC, rck commented on .github/workflows/build-piraeus-client.yaml
> +          DOCKERHUB_IMAGAE=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/piraeus-client
`IMAGAE`? Should not that be `IMAGE`

2021-05-05 06:22 UTC, rck commented
I saw this got some force pushes. So I suggest you get it into a state you are satisfied with and then please squash the commits, this does not need to be a series. Then I'd suggest you add myself as reviewer and assign @WanzenBug , he did the CI/workflow work.

2021-05-05 06:48 UTC, rck requested changes
- see the previous comment for `IMAGAE` vs. `IMAGE`
- by squashing it like this you created a commit message combines the messages from the previous individual message with lots of S-o-b noise. Please rephrase

2021-05-10 15:12 UTC, Jukie commented
Apologies for the delay here. Will finish my updates today.

2021-05-25 09:33 UTC, rck commented
> Apologies for the delay here. Will finish my updates today.

That was 15 days ago. Do you still intend to work in this?

2021-08-18 09:37 UTC, toelke commented
Hey, I would like to take this over (no idea what I'm getting in to). Is there a way for me to highjack this PR with my own branch or should I create a new one?

2021-08-18 09:52 UTC, rck commented
> Hey, I would like to take this over (no idea what I'm getting in to). Is there a way for me to highjack this PR with my own branch or should I create a new one?

I'd say just create a new branch/MR and state in the description that this supersedes this ine

2021-08-18 09:55 UTC, toelke commented
Wilco

2021-08-18 12:38 UTC, WanzenBug commented
Closing this one, see #84

2021-08-18 12:38 UTC, closed without merging